# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux/Qt6', 'FreeBSD/Qt6']
  'require':
    'frameworks/extra-cmake-modules': '@latest-qt6'
    'frameworks/kconfig': '@latest-qt6'
    'frameworks/kconfigwidgets': '@latest-qt6'
    'frameworks/kdoctools': '@latest-qt6'
    'frameworks/ki18n': '@latest-qt6'
    'frameworks/kio': '@latest-qt6'
    'frameworks/kwidgetsaddons': '@latest-qt6'
    'frameworks/kfilemetadata': '@latest-qt6'
    'frameworks/kiconthemes': '@latest-qt6'
    'frameworks/kitemmodels': '@latest-qt6'
    'frameworks/knewstuff': '@latest-qt6'
    'multimedia/libkcddb': '@latest-qt6'

- 'on': ['Linux/Qt5', 'FreeBSD/Qt5']
  'require':
    'frameworks/ki18n': '@stable'
    'frameworks/kxmlgui': '@stable'
    'frameworks/kio': '@stable'
    'frameworks/kfilemetadata': '@stable'
    'frameworks/kiconthemes': '@stable'
    'frameworks/kitemmodels': '@stable'
    'frameworks/kparts': '@stable'
    'frameworks/kcoreaddons': '@stable'
    'frameworks/ktexteditor': '@stable'
    'frameworks/kdoctools': '@stable'
    'frameworks/knewstuff': '@stable'
    'frameworks/kcrash': '@stable'
    'frameworks/extra-cmake-modules': '@stable'
    'multimedia/libkcddb': '@stable'

- 'on': ['Linux', 'FreeBSD']
  'require':
    'graphics/libksane': '@stable'

Options:
  run-tests: True
  require-passing-tests-on: [ 'Linux/Qt5' ]
  run-cppcheck: True
  cppcheck-arguments: '--enable=warning,style,performance'
  cppcheck-ignore-files:
    - src/3rdparty/
