# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['Linux/Qt6', 'FreeBSD/Qt6']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf6'
    'frameworks/kconfig': '@latest-kf6'
    'frameworks/kconfigwidgets': '@latest-kf6'
    'frameworks/kdoctools': '@latest-kf6'
    'frameworks/ki18n': '@latest-kf6'
    'frameworks/kio': '@latest-kf6'
    'frameworks/kwidgetsaddons': '@latest-kf6'
    'frameworks/kfilemetadata': '@latest-kf6'
    'frameworks/kiconthemes': '@latest-kf6'
    'frameworks/kitemmodels': '@latest-kf6'
    'frameworks/knewstuff': '@latest-kf6'
    'multimedia/libkcddb': '@same'
    'graphics/libksane': '@same'

- 'on': ['Linux/Qt5', 'FreeBSD/Qt5']
  'require':
    'frameworks/ki18n': '@stable'
    'frameworks/kxmlgui': '@stable'
    'frameworks/kio': '@stable'
    'frameworks/kfilemetadata': '@stable'
    'frameworks/kiconthemes': '@stable'
    'frameworks/kitemmodels': '@stable'
    'frameworks/kparts': '@stable'
    'frameworks/kcoreaddons': '@stable'
    'frameworks/ktexteditor': '@stable'
    'frameworks/kdoctools': '@stable'
    'frameworks/knewstuff': '@stable'
    'frameworks/kcrash': '@stable'
    'frameworks/extra-cmake-modules': '@stable'
    'multimedia/libkcddb': '@same'
    'graphics/libksane': '@same'

Options:
  run-tests: True
  require-passing-tests-on: [ 'Linux', 'FreeBSD' ]
  run-cppcheck: True
  cppcheck-arguments: '--enable=warning,style,performance'
  cppcheck-ignore-files:
    - src/3rdparty/
