Name=Spanish Ministry of Culture
Name[ca]=El ministeri espanyol de cultura
Name[es]=Ministerio de Cultura de España
Name[pt]=Ministério da Cultura de Espanha
Name[sv]=Spanska Kulturministeriet
Name[uk]=Міністерство культури Іспанії
Name[x-test]=xxSpanish Ministry of Culturexx
Type=data-source
ArgumentKeys=1,2,3,4
Arguments=-t %1,-a %1,-i %1,-i %1
CollectionType=2
FormatType=0
UpdateArgs=-t %{title}
Enabled=false
